[tool.ruff]
line-length = 120
target-version = "py312"            # Match your Python version
extend-select = [
  "F",   # Pyflakes
  "E",   # pycodestyle (errors)
  "W",   # pycodestyle (warnings)
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "C4",  # comprehensions
  "PT",  # pytest style
]
ignore = ["B905"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
python_version = "3.12"