local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    resolution: 0.05
    width: 3.0
    height: 3.0
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      enabled: true
      observation_sources: scan
      scan:
        topic: /scan
        clearing: true
        marking: true
        data_type: LaserScan
        expected_update_rate: 0.1

    inflation_layer:
      enabled: true
      inflation_radius: 0.3